#!/usr/bin/env python
"""
run_eda_report.py — generate the advanced EDA report.

Writes figures plus a markdown report and a machine-readable JSON summary to
outputs/eda/. The same analyses back the notebook (notebooks/EDA.ipynb); this
script runs them headless so the report can be regenerated without opening
Jupyter.

Usage:
    python scripts/run_eda_report.py
    python scripts/run_eda_report.py --quality-sample 400
"""

import argparse
import json
import ntpath
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src import eda  # noqa: E402

SPLITS = PROJECT_ROOT / "data" / "splits"
META = PROJECT_ROOT / "data" / "metadata"
OUT = PROJECT_ROOT / "outputs" / "eda"
MODELS = PROJECT_ROOT / "outputs" / "models"

PALETTE = ["#2E5A88", "#C44E52", "#55A868", "#8172B2", "#CCB974", "#64B5CD"]


def _save(fig, name):
    OUT.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(OUT / name, dpi=140, bbox_inches="tight")
    plt.close(fig)
    return name


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quality-sample", type=int, default=250)
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    md, summary, figs = [], {}, []

    splits = {n: pd.read_csv(SPLITS / f"{n}.csv") for n in ("train", "val", "test")}
    for d in splits.values():
        d["image_name"] = d["image_path"].apply(ntpath.basename)
    registry = pd.read_csv(META / "master_registry.csv", low_memory=False)

    md.append("# Advanced EDA Report\n")
    md.append("Generated by `scripts/run_eda_report.py`. Every figure and table "
              "below is reproducible from the committed splits and registry.\n")

    # ── 1. integrity ────────────────────────────────────────────────────────
    print("[1] split integrity")
    integ = eda.split_integrity(splits)
    sizes = eda.split_sizes(splits)
    cover = eda.registry_coverage(splits, registry)
    summary["integrity"] = {
        "pairs": integ.to_dict("records"),
        "sizes": sizes.to_dict("records"),
        "registry_coverage": cover.to_dict("records"),
    }
    md += ["\n## 1. Split integrity\n",
           "The patient-wise split is the project's central methodological claim. "
           "It is tested here rather than assumed.\n",
           integ.to_markdown(index=False), "\n", sizes.to_markdown(index=False), "\n",
           "\n**Metadata coverage.** Any statistic drawn from registry columns "
           "(findings, view position, demographics) describes only this share of "
           "each split:\n", cover.to_markdown(index=False), "\n"]

    # ── 2. multi-label structure ────────────────────────────────────────────
    print("[2] multi-label structure")
    co, co_meta = eda.cooccurrence_with(registry, "Pneumonia")
    summary["cooccurrence"] = {"meta": co_meta, "table": co.head(10).to_dict("records")}
    md += ["\n## 2. Why the hard negatives are hard\n",
           f"Of the {co_meta['images_with_target']} films tagged Pneumonia, only "
           f"**{co_meta['target_alone_%']}%** carry that label alone - "
           f"**{co_meta['with_cofinding_%']}%** carry at least one co-finding.\n",
           co.head(10).to_markdown(index=False), "\n",
           "\nThe findings a model must separate from pneumonia are frequently "
           "printed on the *same image*. A film tagged `Infiltration|Pneumonia` is a "
           "positive while one tagged `Infiltration` alone is a negative, and the two "
           "can be radiographically indistinguishable. This is a data-level "
           "explanation for the difficulty ordering the training curriculum uses.\n"]

    fig, ax = plt.subplots(figsize=(9, 4.5))
    top = co.head(10).iloc[::-1]
    ax.barh(top.co_finding, top["%_of_pneumonia"], color=PALETTE[0])
    ax.set_xlabel("% of Pneumonia-tagged images also carrying this finding")
    ax.set_title("Pneumonia co-occurrence in NIH labels")
    ax.grid(axis="x", alpha=0.3)
    figs.append(_save(fig, "adv_cooccurrence.png"))

    joined = eda.attach_metadata(splits["train"], registry)
    fpi = eda.findings_per_image(joined)
    negc = eda.negatives_carrying_finding(
        joined, ["Infiltration", "Effusion", "Edema", "Atelectasis", "Consolidation"])
    summary["findings_per_image"] = fpi.to_dict("records")
    summary["negatives_carrying_finding"] = negc.to_dict("records")
    md += ["\n### Findings per image, by assigned class\n",
           fpi.to_markdown(index=False), "\n",
           "\n### Negatives carrying a pneumonia-adjacent finding\n",
           negc.to_markdown(index=False), "\n"]

    # ── 3. distribution shift ───────────────────────────────────────────────
    print("[3] distribution shift across splits")
    share, drift = eda.class_share_across_splits(splits)
    summary["class_share"] = share.to_dict()
    summary["split_drift_chi2"] = drift
    verdict = ("no detectable drift" if drift["p_value"] > 0.05
               else "classes are NOT distributed identically across splits")
    md += ["\n## 3. Distribution shift across splits\n",
           share.to_markdown(), "\n",
           f"\nChi-square across splits: chi2={drift['chi2']}, p={drift['p_value']:.4g}, "
           f"Cramer's V={drift['cramers_v']} - {verdict}.\n"]

    fig, ax = plt.subplots(figsize=(11, 4.5))
    share.plot(kind="bar", ax=ax, color=PALETTE[:3], width=0.8)
    ax.set_ylabel("% of split")
    ax.set_title("Class share by split")
    ax.grid(axis="y", alpha=0.3)
    ax.legend(title="")
    plt.xticks(rotation=45, ha="right")
    figs.append(_save(fig, "adv_class_share_by_split.png"))

    # ── 4. confounds ────────────────────────────────────────────────────────
    print("[4] confound tests")
    md += ["\n## 4. Confounds and shortcut risk\n",
           "A factor that predicts the label without being the pathology is a "
           "shortcut the model can learn instead of the disease. Chi-square gives "
           "significance; Cramer's V gives effect size, which matters because "
           "chi-square grows with sample size alone.\n"]
    conf_rows = []
    for factor in ("view_position", "patient_gender"):
        r = eda.association_test(joined, factor)
        if r is None:
            continue
        ct = r.pop("contingency")
        conf_rows.append(r)
        md += [f"\n**{factor}** - n={r['n']}, chi2={r['chi2']}, p={r['p_value']:.4g}, "
               f"Cramer's V={r['cramers_v']}\n",
               f"\nPositive rate by level: {r['pos_rate_by_level_%']}\n"]
        if factor == "view_position":
            fig, ax = plt.subplots(figsize=(6, 4))
            lv = list(r["pos_rate_by_level_%"])
            ax.bar(lv, [r["pos_rate_by_level_%"][k] for k in lv], color=PALETTE[1])
            ax.set_ylabel("pneumonia rate (%)")
            ax.set_title("Pneumonia rate by view position")
            ax.grid(axis="y", alpha=0.3)
            figs.append(_save(fig, "adv_view_position_confound.png"))
    age = eda.numeric_group_test(joined, "patient_age")
    if age:
        conf_rows.append(age)
        md += [f"\n**patient_age** - median {age['median_pos']} (pos) vs "
               f"{age['median_neg']} (neg), Mann-Whitney p={age['p_value']:.4g}, "
               f"Cohen's d={age['cohens_d']}\n"]
    summary["confounds"] = conf_rows

    # ── 5. image quality ────────────────────────────────────────────────────
    print(f"[5] image quality on {args.quality_sample} sampled images")
    q = eda.image_quality_sample(splits["train"].image_path, n=args.quality_sample)
    if not q.empty:
        desc = q[["mean_intensity", "std_intensity", "border_frac"]].describe().round(3)
        summary["image_quality"] = {
            "n_sampled": int(len(q)),
            "border_frac_mean": round(float(q.border_frac.mean()), 4),
            "border_frac_max": round(float(q.border_frac.max()), 4),
            "pct_border_over_5": round(100 * float((q.border_frac > 0.05).mean()), 1),
            "sizes": q.groupby(["width", "height"]).size().to_dict().__str__(),
        }
        md += ["\n## 5. Image-level quality\n", desc.to_markdown(), "\n",
               f"\nBorder fraction (share of the frame outside the non-black bounding "
               f"box) averages {100*q.border_frac.mean():.1f}% but reaches "
               f"{100*q.border_frac.max():.1f}% on the worst sampled image, with "
               f"{100*(q.border_frac>0.05).mean():.0f}% of images above 5%. Those "
               f"films spend much of their resolution on empty frame after resizing.\n"]
        fig, axes = plt.subplots(1, 2, figsize=(11, 4))
        axes[0].hist(q.border_frac * 100, bins=30, color=PALETTE[2], edgecolor="white")
        axes[0].set_xlabel("border fraction (%)")
        axes[0].set_title("Wasted frame area")
        axes[1].hist(q.mean_intensity, bins=30, color=PALETTE[3], edgecolor="white")
        axes[1].set_xlabel("mean intensity")
        axes[1].set_title("Global brightness")
        for a in axes:
            a.grid(axis="y", alpha=0.3)
        figs.append(_save(fig, "adv_image_quality.png"))

    dups = eda.duplicate_report(registry)
    summary["duplicate_hashes"] = int(len(dups))
    md += [f"\n**Duplicate image hashes in the registry:** {len(dups)}\n"]

    # ── 6. negative difficulty (needs model scores) ─────────────────────────
    print("[6] negative difficulty")
    prob_files = sorted(MODELS.glob("*/val_probs*.csv"))
    if prob_files:
        pf = prob_files[0]
        p = pd.read_csv(pf)
        merged = splits["val"][["image_path", "class_name", "label"]].merge(
            p[["image_path", "p_tta"]], on="image_path", how="inner")
        tbl, s = eda.negative_difficulty(merged, merged["p_tta"])
        summary["negative_difficulty"] = {"source": pf.name, "summary": s,
                                          "table": tbl.to_dict("records")}
        md += ["\n## 6. Negative-class difficulty\n",
               f"Scores from `{pf.relative_to(PROJECT_ROOT)}`.\n",
               tbl.to_markdown(index=False), "\n",
               f"\nPositives average {s['positive_mean_score']}. Against all negatives "
               f"AUC is {s['auc_vs_all_negatives']}; against the three hardest "
               f"({', '.join(s['hardest_3'])}) it is {s['auc_vs_hardest_3']}, versus "
               f"{s['auc_vs_rest']} against the rest. This is the measurement the "
               f"training curriculum's phase ordering is built on.\n"]
        fig, ax = plt.subplots(figsize=(9, 4.5))
        t = tbl.iloc[::-1]
        ax.barh(t["class_name"], t["mean"], color=PALETTE[1])
        ax.axvline(s["positive_mean_score"], color=PALETTE[0], ls="--",
                   label=f"Pneumonia mean = {s['positive_mean_score']}")
        ax.set_xlabel("mean predicted pneumonia score")
        ax.set_title("Negative-class confusability")
        ax.legend()
        ax.grid(axis="x", alpha=0.3)
        figs.append(_save(fig, "adv_negative_difficulty.png"))
    else:
        md += ["\n## 6. Negative-class difficulty\n",
               "Skipped: no `outputs/models/*/val_probs*.csv` found. Run "
               "`scripts/dump_predictions.py` first.\n"]

    # ── write ───────────────────────────────────────────────────────────────
    md += ["\n---\n\n## Figures\n"] + [f"- `{f}`\n" for f in figs]
    (OUT / "advanced_eda_report.md").write_text("".join(md), encoding="utf-8")
    (OUT / "advanced_eda_summary.json").write_text(
        json.dumps(summary, indent=2, default=str), encoding="utf-8")
    print(f"\nwrote {OUT / 'advanced_eda_report.md'}")
    print(f"wrote {OUT / 'advanced_eda_summary.json'}")
    print(f"figures: {len(figs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
